### ISSUE TITLE
[Bug]: latest neoforge crashes machine mod

### ISSUE THREAD

**Issue by Abalieno** [Soaryn/XyCraftTracker#40]
### Mod Title

XyCraft Machines

### Minecraft Version

1.21

### Severity

Crashing

### Describe the Suggestion

Works with neoforge 21.0.9, doesn't anymore with 21.0.10

### Reproduction Steps

Startup crash

### Additional Context

Exception message: java.lang.NoSuchMethodError: 'net.minecraft.world.item.Rarity net.minecraft.world.item.Rarity.create(java.lang.String, net.minecraft.resources.ResourceLocation, java.util.function.UnaryOperator)'

at TRANSFORMER/xycraft_core@0.7.20/tv.soaryn.xycraft.api.content.capabilities.modular.ModuleType.<clinit>(ModuleType.java:6) ~[?:?] {re:classloading}

**Comment by Soaryn** [comment]
This is due to a change in Neo this morning, will look into it soon. For now use the working version that you found. Sorry for the inconvenience. This is expecteded while Neo is still in beta mode for 1.21

**Comment by Soaryn** [comment]
Fixed in `v0.7.21+`
